from fastmcp.resources.function_resource import resource


@resource("info://tools")
def available_tools() -> str:
    """Describes all available tools in this MCP server."""

    return (
        "This MCP server has the following tools:\n"
        "- compress_pdf: Compress a PDF using the PDF4me API. "
        "Accepts a source PDF file path and returns compressed PDF output. "
        "Supports optimization profiles: Web, Print, and Screen.\n"
        "- compress_image: Compress an image via /api/v2/CompressImage. "
        "image_file_path, image_type (JPG, PNG, WebP), compression_level (Max, Medium, Low); optional output path.\n"
        "- create_barcode: Create a barcode or QR code PNG via PDF4me CreateBarcode. "
        "Parameters: text, barcodeType (e.g. qrCode, code128), hideText; optional output path.\n"
        "- add_attachment_to_pdf: Embed files into a PDF via AddAttachmentToPdf. "
        "pdf_file_path, attachment_file_paths (list), optional request_doc_name, output path.\n"
        "- add_barcode_to_pdf: Draw a barcode/QR on PDF pages via /api/v2/addbarcode. "
        "pdf_file_path, text, barcodeType, pages, alignX, alignY, hideText; optional sizing.\n"
        "- add_form_fields_to_pdf: Add a TextBox or CheckBox field via /api/v2/AddFormField. "
        "pdf_file_path, field_name, initial_value, position_x/y, size, pages, form_field_type.\n"
        "- add_html_header_footer_to_pdf: Add HTML header/footer via /api/v2/AddHtmlHeaderFooter. "
        "pdf_file_path, html_content, header_footer_location (Header/Footer/Both); optional pages, margins.\n"
        "- add_image_stamp_to_pdf: Image stamp/watermark via /api/v2/ImageStamp. "
        "pdf_file_path, image_file_path, alignX, alignY; optional pages, sizes, margins, opacity.\n"
        "- add_image_watermark_to_image: Overlay watermark image on image via AddImageWatermarkToImage. "
        "image_file_path, watermark_image_file_path, position; optional opacity, offsets, position_x/y, rotation.\n"
        "- add_text_watermark_to_image: Text watermark on image via /api/v2/AddTextWatermarkToImage. "
        "image_file_path, watermark_text, text_position, text_font_family, is_underline, is_italic; "
        "optional font size, colour, bold, opacity, rotation, position_x/y.\n"
        "- crop_image: Crop image via /api/v2/CropImage with schemaVal Border or Rectangle. "
        "image_file_path, crop_type; Border uses left/right/top/bottom borders, Rectangle uses x/y/width/height.\n"
        "- add_margin_to_pdf: Add page margins via /api/v2/AddMargin. "
        "pdf_file_path and optional margin_left/right/top/bottom in millimeters; optional output path.\n"
        "- add_page_number_to_pdf: Add page numbers via /api/v2/AddPageNumber. "
        "pdf_file_path, page_number_format, align_x/align_y; optional margins and font styling.\n"
        "- add_text_stamp_to_pdf: Text stamp/watermark via /api/v2/Stamp. "
        "pdf_file_path, text, pages, align_x/align_y, fonts, margins (mm/px strings), opacity string, rotation.\n"
        "- delete_blank_pages_from_pdf: Remove blank pages via /api/v2/DeleteBlankPages. "
        "pdf_file_path and delete_page_option (NoTextNoImages, NoText, NoImages); saves cleaned PDF.\n"
        "- extract_resources: Extract text/images from PDF via /api/v2/ExtractResources. "
        "pdf_file_path, extract_text, extract_images; optional output_dir; saves JSON, text file, and images.\n"
        "- extract_table_from_pdf: Extract tables from PDF via /api/v2/ExtractTableFromPdf. "
        "pdf_file_path; optional output_dir; saves extracted_tables.json, per-table JSON and CSV.\n"
        "- extract_text_by_expression: Regex text extraction via /api/v2/ExtractTextByExpression. "
        "pdf_file_path, expression, page_sequence; optional output_dir; saves JSON, matches txt/csv.\n"
        "- extract_attachment_from_pdf: Extract embedded attachments via /api/v2/ExtractAttachmentFromPdf. "
        "pdf_file_path; optional output_dir; JSON outputDocuments decoded to files, or ZIP saved and unpacked.\n"
        "- parse_document: Template-based PDF parsing via /api/v2/ParseDocument. "
        "pdf_file_path, template_id or template_name, optional parse_id (UUID), output_dir; saves parsed_document.json.\n"
        "- classify_document: Classify PDF by content via /api/v2/ClassifyDocument. "
        "pdf_file_path; optional output_dir; saves classified_document.json (documentType, category, confidence, metadata).\n"
        "- process_invoice (AI-Invoice Parser): via /api/v2/ProcessInvoice. "
        "Exactly one of pdf_file_path (local pdf/png/jpeg) or doc_content (base64, blob id, or URL); "
        "doc_name optional with file path (defaults to basename), required with doc_content; "
        "optional custom_field_keys (omit when unused); IsAsync true with 202 polling; saves process_invoice.json.\n"
        "- process_bank_cheque (AI-Process Bank Cheque): via /api/v2/ProcessBankCheque. "
        "Exactly one of pdf_file_path or doc_content; doc_name optional (defaults to basename or cheque.pdf); "
        "isAsync and CustomFieldKeys (PascalCase) in the API body when keys are sent; 202 polling; saves process_bank_cheque.json.\n"
        "- flatten_pdf: Flatten a PDF using the PDF4me FlattenPdf API. "
        "Accepts a local PDF path; optional async 202 polling, output directory, and file name; saves to disk.\n"
        "- linearize_pdf: Linearize a PDF using the PDF4me LinearizePdf API. "
        "Accepts a local PDF path and saves a linearized PDF. "
        "Supports optimization presets (web, Max, Print, Default, WebMax, PrintMax, PrintGray, Compress, CompressMax), "
        "optional async 202 polling, and optional output directory and file name.\n"
        "- convert_pdf_to_pdfa: Convert a PDF to PDF/A using the PDF4me PdfA API. "
        "Accepts a local PDF path, compliance (PdfA1a–PdfA3u), allow upgrade/downgrade, optional async 202 polling, "
        "and optional output path; saves the PDF/A to disk.\n"
        "- convert_html_to_pdf: Convert a local HTML file (.html/.htm) to PDF using the PDF4me ConvertHtmlToPdf API. "
        "Layout, format, scale, margins, print options, optional async 202 polling (job URL resolved against API base), "
        "optional output directory and file name; saves the PDF to disk.\n"
        "- convert_url_to_pdf: Convert a web URL to PDF using the PDF4me ConvertUrlToPdf API. "
        "Required input is web_url only (no local source file); auth, layout, margins, scale, optional async 202 polling; "
        "optional output directory and file name (supports output_dir/outputDir aliases); saves the PDF to disk.\n"
        "- convert_json_to_excel: Convert a local JSON file to XLSX using the PDF4me ConvertJsonToExcel API. "
        "Worksheet name, title and number/date options, optional async 202 polling (Location resolved to absolute URL), "
        "optional output directory and file name; saves the workbook to disk.\n"
        "- convert_pdf_to_excel: Convert a local PDF file to XLSX using the PDF4me ConvertPdfToExcel API. "
        "Quality (Draft/High), merge sheets, language, OCR when needed, optional async 202 polling (Location resolved), "
        "optional output directory and file name; saves the workbook to disk.\n"
    )
