from fastmcp.resources.function_resource import resource


@resource("info://tools")
def available_tools() -> str:
    """Describes all available tools in this MCP server."""

    return (
        "This MCP server has the following tools:\n"
        "- compress_pdf: Compress a PDF using the PDF4me API. "
        "Accepts a source PDF file path and returns compressed PDF output. "
        "Supports optimization profiles: Web, Print, and Screen.\n"
        "- compress_image: Compress an image via /api/v2/CompressImage. "
        "image_file_path, image_type (JPG, PNG, WebP), compression_level (Max, Medium, Low); optional output path.\n"
        "- create_barcode: Create a barcode or QR code PNG via PDF4me CreateBarcode. "
        "Parameters: text, barcodeType (e.g. qrCode, code128), hideText; optional output path.\n"
        "- add_attachment_to_pdf: Embed files into a PDF via AddAttachmentToPdf. "
        "pdf_file_path, attachment_file_paths (list), optional request_doc_name, output path.\n"
        "- add_barcode_to_pdf: Draw a barcode/QR on PDF pages via /api/v2/addbarcode. "
        "pdf_file_path, text, barcodeType, pages, alignX, alignY, hideText; optional sizing.\n"
        "- add_form_fields_to_pdf: Add a TextBox or CheckBox field via /api/v2/AddFormField. "
        "pdf_file_path, field_name, initial_value, position_x/y, size, pages, form_field_type.\n"
        "- add_html_header_footer_to_pdf: Add HTML header/footer via /api/v2/AddHtmlHeaderFooter. "
        "pdf_file_path, html_content, header_footer_location (Header/Footer/Both); optional pages, margins.\n"
        "- add_image_stamp_to_pdf: Image stamp/watermark via /api/v2/ImageStamp. "
        "pdf_file_path, image_file_path, alignX, alignY; optional pages, sizes, margins, opacity.\n"
        "- add_image_watermark_to_image: Overlay watermark image on image via AddImageWatermarkToImage. "
        "image_file_path, watermark_image_file_path, position; optional opacity, offsets, position_x/y, rotation.\n"
        "- add_text_watermark_to_image: Text watermark on image via /api/v2/AddTextWatermarkToImage. "
        "image_file_path, watermark_text, text_position, text_font_family, is_underline, is_italic; "
        "optional font size, colour, bold, opacity, rotation, position_x/y.\n"
        "- crop_image: Crop image via /api/v2/CropImage with schemaVal Border or Rectangle. "
        "image_file_path, crop_type; Border uses left/right/top/bottom borders, Rectangle uses x/y/width/height.\n"
        "- add_margin_to_pdf: Add page margins via /api/v2/AddMargin. "
        "pdf_file_path and optional margin_left/right/top/bottom in millimeters; optional output path.\n"
        "- add_page_number_to_pdf: Add page numbers via /api/v2/AddPageNumber. "
        "pdf_file_path, page_number_format, align_x/align_y; optional margins and font styling.\n"
        "- add_text_stamp_to_pdf: Text stamp/watermark via /api/v2/Stamp. "
        "pdf_file_path, text, pages, align_x/align_y, fonts, margins (mm/px strings), opacity string, rotation.\n"
        "- delete_blank_pages_from_pdf: Remove blank pages via /api/v2/DeleteBlankPages. "
        "pdf_file_path and delete_page_option (NoTextNoImages, NoText, NoImages); saves cleaned PDF.\n"
        "- extract_resources: Extract text/images from PDF via /api/v2/ExtractResources. "
        "pdf_file_path, extract_text, extract_images; optional output_dir; saves JSON, text file, and images.\n"
        "- extract_table_from_pdf: Extract tables from PDF via /api/v2/ExtractTableFromPdf. "
        "pdf_file_path; optional output_dir; saves extracted_tables.json, per-table JSON and CSV.\n"
        "- extract_text_by_expression: Regex text extraction via /api/v2/ExtractTextByExpression. "
        "pdf_file_path, expression, page_sequence; optional output_dir; saves JSON, matches txt/csv.\n"
        "- extract_form_data_from_pdf: Extract PDF form fields and values via /api/v2/ExtractPdfFormData. "
        "pdf_file_path; optional request_doc_name and output_dir; saves extracted_form_data.json.\n"
        "- extract_text_from_word: Extract text from Word via /api/v2/ExtractTextFromWord. "
        "word_file_path, start_page_number, end_page_number, remove_comments, remove_header_footer, accept_changes; "
        "optional request_doc_name, output_dir, output_file_name.\n"
        "- extract_pages_from_pdf: Extract selected PDF pages via /api/v2/Extract. "
        "pdf_file_path, page_numbers; optional request_doc_name and output path; saves extracted PDF.\n"
        "- find_and_replace_text: Find and replace PDF text via /api/v2/FindAndReplace. "
        "pdf_file_path, old_text, new_text, page_sequence; optional request_doc_name and output path.\n"
        "- merge_multiple_pdfs: Merge multiple PDFs via /api/v2/Merge. "
        "pdf_file_paths (list, min 2), optional request_doc_name and output path; saves merged PDF.\n"
        "- merge_pdf_overlay: Merge two PDFs as overlay via /api/v2/MergeOverlay. "
        "base_pdf_file_path, overlay_pdf_file_path; optional output path; saves merged PDF.\n"
        "- split_pdf: Split PDF via /api/v2/SplitPdf. "
        "pdf_file_path, split_action (RecurringSplitAfterPage|SplitAfterPage|SplitSequence|SplitRanges), "
        "with matching split parameters; optional output_dir; saves split PDFs and raw JSON.\n"
        "- split_pdf_by_text: Split PDF by matching text via /api/v2/SplitByText. "
        "pdf_file_path, text, split_text_page (before/after), file_naming; optional output_dir; "
        "saves split PDFs and raw JSON.\n"
        "- split_pdf_by_swiss_qr: Split PDF by Swiss QR via /api/v2/FlowV2/SplitPdfByBarcode. "
        "pdf_file_path, split_qr_page, pdf_render_dpi, combine_pages_with_same_barcodes, return_as_zip; "
        "optional output_dir; saves split PDFs (or ZIP) and raw JSON.\n"
        "- split_pdf_by_barcode: Split PDF by barcode via /api/v2/SplitByBarcode. "
        "pdf_file_path, barcode_string, barcode_filter, barcode_type, split_barcode_page, "
        "combine_pages_with_same_consecutive_barcodes, pdf_render_dpi; optional output_dir; saves split PDFs and raw JSON.\n"
        "- flip_image: Flip an image via /api/v2/FlipImage. "
        "image_file_path, orientation (horizontal|vertical); optional request_doc_name and output path.\n"
        "- extract_attachment_from_pdf: Extract embedded attachments via /api/v2/ExtractAttachmentFromPdf. "
        "pdf_file_path; optional output_dir; JSON outputDocuments decoded to files, or ZIP saved and unpacked.\n"
        "- parse_document: Template-based PDF parsing via /api/v2/ParseDocument. "
        "pdf_file_path, template_id or template_name, optional parse_id (UUID), output_dir; saves parsed_document.json.\n"
        "- classify_document: Classify PDF by content via /api/v2/ClassifyDocument. "
        "pdf_file_path; optional output_dir; saves classified_document.json (documentType, category, confidence, metadata).\n"
        "- get_document_from_pdf4me: Subscribe webhook callback via /api/v2/WebhookSubscribe. "
        "callback_url and doc_name; optional output path; saves webhook response JSON.\n"
        "- process_invoice (AI-Invoice Parser): via /api/v2/ProcessInvoice. "
        "Exactly one of pdf_file_path (local pdf/png/jpeg) or doc_content (base64, blob id, or URL); "
        "doc_name optional with file path (defaults to basename), required with doc_content; "
        "optional custom_field_keys (omit when unused); IsAsync true with 202 polling; saves process_invoice.json.\n"
        "- process_bank_cheque (AI-Process Bank Cheque): via /api/v2/ProcessBankCheque. "
        "Exactly one of pdf_file_path or doc_content; doc_name optional (defaults to basename or cheque.pdf); "
        "isAsync and CustomFieldKeys (PascalCase) in the API body when keys are sent; 202 polling; saves process_bank_cheque.json.\n"
        "- process_contract (AI-Process Contract): via /api/v2/ProcessContract. "
        "Exactly one of pdf_file_path or doc_content; doc_name optional (basename or contract.pdf); "
        "body is only docContent, docName, IsAsync; no custom fields; 202 polling; saves process_contract.json.\n"
        "- process_credit_card (AI-Process Credit Card): via /api/v2/ProcessCreditCard. "
        "Exactly one of pdf_file_path or doc_content (Base64/data URL/blob/URL; data URL prefix stripped); "
        "doc_name optional (basename or credit_card.png); IsAsync and CustomFieldKeys when keys non-empty; "
        "202 polling; saves process_credit_card.json.\n"
        "- process_health_card (AI-Process Health Card): via /api/v2/ProcessHealthCard. "
        "Exactly one of pdf_file_path or doc_content (Base64/data URL/blob/URL; data URL prefix stripped); "
        "doc_name optional (basename or health_card.jpeg); body only docContent, docName, IsAsync; "
        "202 polling; saves process_health_card.json.\n"
        "- process_marriage_certificate (AI-Process Marriage Certificate): via /api/v2/ProcessMarriageCertificate. "
        "Exactly one of pdf_file_path or doc_content (data URL prefix stripped); doc_name optional (basename or marriage_certificate.pdf); "
        "IsAsync true; optional verify_authenticity (VerifyAuthenticity only when true); CustomFieldKeys when keys non-empty; "
        "202 polling; saves process_marriage_certificate.json.\n"
        "- process_mortgage_document (AI-Process Mortgage Document): via /api/v2/ProcessMortgageDocument. "
        "Exactly one of pdf_file_path (.pdf with %PDF header) or doc_content (URL/blob or PDF base64; "
        f"long base64 must start with JVBERi0x after data URL strip); isAsync camelCase; optional documentType; "
        "CustomFieldKeys when keys non-empty; 202 polling; saves process_mortgage_document.json.\n"
        "- process_pay_stub (AI-Process Pay Stub): via /api/v2/ProcessPayStub. "
        "Exactly one of pdf_file_path or doc_content (Base64/data URL/blob/URL; data URL prefix stripped; PNG/JPEG OK); "
        "doc_name optional (basename or pay_stub.png); IsAsync and CustomFieldKeys when keys non-empty; "
        "202 polling; saves process_pay_stub.json.\n"
        "- process_bank_statement (AI-Process Bank Statement / processBankStatement): via /api/v2/ProcessBankStatement. "
        "Exactly one of pdf_file_path or doc_content; docName logical name; analyzePatterns and isAsync; "
        "optional bankName; customFieldKeys camelCase when keys set (list and/or CSV merged); optional profiles (sanitized); "
        "202 polling; saves process_bank_statement.json.\n"
        "- process_order (AI-Process Order / processOrder): via /api/v2/ProcessOrder. "
        "Exactly one of pdf_file_path or doc_content; docName logical name (basename or order.pdf); "
        "isAsync true; optional profiles (sanitized); 202 polling; saves process_order.json.\n"
        "- process_receipt (AI-Process Receipt / processReceipt): via /api/v2/ProcessReceipt. "
        "Exactly one of pdf_file_path or doc_content; docName from file basename, URL path segment, or doc_name; "
        "analyzeItems, extractMerchantInfo, calculateTotals, isAsync; optional receiptType (omit if none/empty); "
        "customFieldKeys camelCase when keys set (list and/or CSV); optional profiles; 202 polling; saves process_receipt.json.\n"
        "- process_shipping_label (AI-Process Shipping Label / processShippingLabel): via /api/v2/ProcessShippingLabel. "
        "Exactly one of pdf_file_path or doc_content; docName rules (file basename, URL: doc_name else path segment, "
        f"else shipping_label.pdf); isAsync true; optional profiles (sanitized); 202 polling; saves process_shipping_label.json.\n"
        "- process_tax_document (AI-Process Tax Document / processTaxDocument): via /api/v2/ProcessTaxDocument. "
        "Exactly one of pdf_file_path or doc_content; docName is doc_name as provided (not basename/URL), default tax_document.pdf; "
        "isAsync true; optional taxModel (omit if none/empty); customFieldKeys camelCase when keys set (list and/or CSV); "
        "optional profiles; 202 polling; saves process_tax_document.json.\n"
        "- process_universal_document (AI - Universal Document Data Extraction / processUniversalDocument): "
        "via /api/v2/ProcessUniversalDocument. Exactly one of pdf_file_path or doc_content; docName from inputDocName "
        "chain then doc_name then document.pdf; required fields (list and/or CSV); mode 0 Standard or 1 Strict; "
        "isAsync true; optional documentType and profiles; 202 polling; saves process_universal_document.json.\n"
        "- flatten_pdf: Flatten a PDF using the PDF4me FlattenPdf API. "
        "Accepts a local PDF path; optional async 202 polling, output directory, and file name; saves to disk.\n"
        "- repair_pdf: Repair a PDF using the PDF4me RepairPdf API. "
        "Accepts a local PDF path; optional async 202 polling, output directory, and file name; saves the repaired PDF to disk.\n"
        "- rotate_pdf: Rotate all pages of a PDF using the PDF4me Rotate API. "
        "Accepts rotationType (NoRotation, Clockwise, CounterClockwise, UpsideDown); optional async 202 polling ; "
        "optional output directory and file name; saves the rotated PDF to disk.\n"
        "- rotate_pdf_page: Rotate selected pages of a PDF using the PDF4me RotatePage API. "
        "Requires a page spec (e.g. 1 or 1,3,5 or 2-4) and rotationType; optional async 202 polling ; "
        "optional output directory and file name; saves the PDF to disk.\n"
        "- sign_pdf: Add a signature image to a PDF using the PDF4me SignPdf API. "
        "Accepts PDF path plus signature image path; layout and margin options; optional async 202 polling ; "
        "optional output directory and file name; saves the signed PDF to disk.\n"
        "- protect_pdf: Password-protect a local PDF using the PDF4me Protect API. "
        "Requires password and pdf_permission (e.g. All); optional async 202 polling, output directory, and file name; saves the protected PDF to disk.\n"
        "- unlock_pdf: Remove password protection from a local PDF using the PDF4me Unlock API. "
        "Requires the current open password; optional async 202 polling, output directory, and file name; saves the unlocked PDF to disk.\n"
        "- linearize_pdf: Linearize a PDF using the PDF4me LinearizePdf API. "
        "Accepts a local PDF path and saves a linearized PDF. "
        "Supports optimization presets (web, Max, Print, Default, WebMax, PrintMax, PrintGray, Compress, CompressMax), "
        "optional async 202 polling, and optional output directory and file name.\n"
        "- convert_pdf_to_pdfa: Convert a PDF to PDF/A using the PDF4me PdfA API. "
        "Accepts a local PDF path, compliance (PdfA1a–PdfA3u), allow upgrade/downgrade, optional async 202 polling, "
        "and optional output path; saves the PDF/A to disk.\n"
        "- convert_html_to_pdf: Convert a local HTML file (.html/.htm) to PDF using the PDF4me ConvertHtmlToPdf API. "
        "Layout, format, scale, margins, print options, optional async 202 polling , "
        "optional output directory and file name; saves the PDF to disk.\n"
        "- convert_url_to_pdf: Convert a web URL to PDF using the PDF4me ConvertUrlToPdf API. "
        "Required input is web_url only (no local source file); auth, layout, margins, scale, optional async 202 polling; "
        "optional output directory and file name (supports output_dir/outputDir aliases); saves the PDF to disk.\n"
        "- convert_json_to_excel: Convert a local JSON file to XLSX using the PDF4me ConvertJsonToExcel API. "
        "Worksheet name, title and number/date options, optional async 202 polling , "
        "optional output directory and file name; saves the workbook to disk.\n"
        "- convert_pdf_to_excel: Convert a local PDF file to XLSX using the PDF4me ConvertPdfToExcel API. "
        "Quality (Draft/High), merge sheets, language, OCR when needed, optional async 202 polling , "
        "optional output directory and file name; saves the workbook to disk.\n"
        "- convert_pdf_to_powerpoint: Convert a local PDF file to PPTX using the PDF4me ConvertPdfToPowerPoint API. "
        "Quality (Draft/High), language, OCR when needed, merge sheets, optional async 202 polling , "
        "optional output directory and file name; saves the presentation to disk.\n"
        "- convert_md_to_pdf: Convert a local Markdown file (.md) to PDF using the PDF4me ConvertMdToPdf API. "
        "Supports optional async 202 polling , "
        "and optional output directory and file name; saves the PDF to disk.\n"
        "- convert_pdf_to_word: Convert a local PDF file to DOCX using the PDF4me ConvertPdfToWord API. "
        "Quality (Draft/High), merge sheets, language, OCR when needed, optional async 202 polling , "
        "optional output directory and file name; saves the Word document to disk.\n"
        "- convert_word_to_pdf_form: Convert a local DOCX file to a fillable PDF form using the PDF4me ConvertWordToPdfForm API. "  
        "Supports optional async 202 polling , "
        "and optional output directory and file name; saves the PDF to disk.\n"
        "- fill_pdf_form: Fill fields in a local PDF form using the PDF4me FillPdfForm API. "
        "Accepts a local PDF path plus form_data key/value JSON, supports optional async 202 polling, "
        "and optional output directory and file name; saves the filled PDF to disk.\n"
        "- get_pdf_metadata: Extract metadata from a local PDF using the PDF4me GetPdfMetadata API. "
        "Supports both sync and async processing (optional 202 polling with Location resolution), "
        "and returns structured metadata JSON (title, author, page info, dates, and security fields).\n"
        "- get_image_metadata: Extract metadata from a local JPG/PNG image using the PDF4me GetImageMetadata API. "
        "Supports both sync and async processing (optional 202 polling with Location resolution), "
        "and returns structured metadata JSON (image properties and available EXIF fields).\n"
        "- convert_image_format: Convert a local image between BMP/GIF/JPG/PNG/TIFF using the PDF4me "
        "ConvertImageFormat API. Supports sync/async processing (optional 202 polling with Location "
        "resolution), optional output directory and file name; saves the converted image to disk.\n"
        "- resize_image: Resize a local image using the PDF4me ResizeImage API (Percentage or Specific). "
        "Supports resize percentage or width/height, maintain aspect ratio, "
        "sync/async (optional 202 polling with Location resolution), optional output path; saves the image to disk.\n"
        "- rotate_image: Rotate a local image using the PDF4me RotateImage API. "
        "Supports rotation angle, background color, proportionate resize, sync/async (optional 202 polling with Location resolution), "
        "optional output directory and file name; saves the rotated image to disk.\n"
        "- convert_to_pdf: Convert a local document (e.g. DOCX, PPTX, XLSX, image, text formats) to PDF "
        "using the PDF4me ConvertToPdf API. Supports sync/async processing (optional 202 polling with "
        "Location resolution), optional output directory and file name; saves the PDF to disk.\n"
        "- convert_visio_to_pdf: Convert a local Visio file (.vsdx/.vsd/.vsdm) to PDF using the PDF4me "
        "ConvertVisio API (schemaVal=PDF). Supports PDF options, sync/async processing (optional 202 polling "
        "with Location resolution), optional output directory and file name; saves the PDF to disk.\n"
        "- create_images_from_pdf: Render PDF pages to image files using the PDF4me CreateImages API. "
        "Supports page selection (single, list, range, or all), output width in pixels, and image format "
        "(e.g. jpeg/png/tiff). Optional async 202 polling with Location resolution; saves one image per page.\n"
        "- create_swiss_qr_bill: Create a Swiss QR bill payment section on a PDF using the PDF4me CreateSwissQrBill API. "
        "Requires PDF input plus core billing fields (e.g. iban, creditor name/address type); supports optional "
        "currency/language/reference settings, optional async 202 polling, and optional output path; saves the PDF to disk.\n"
        "- create_zugferd_invoice: Create a ZUGFeRD e-invoice using the PDF4me CreateZugferdInvoice API. "
        "Supports XML/JSON/CSV invoice input, output mode (XmlWithPdf or XmlOnly), conformance level, and language; "
        "for XmlWithPdf it also accepts a source PDF. Saves PDF or XML output to disk.\n"
        "- delete_pdf_pages: Remove selected pages from a local PDF using the PDF4me DeletePages API. "
        "Accepts page expressions (e.g. 2, 1,3,5, 2-4), optional async 202 polling, and optional output path; saves the PDF to disk.\n"
        "- extract_text_from_image: Extract OCR text from a local image using the PDF4me ImageExtractText API. "
        "Supports common image formats, optional async 202 polling with Location resolution, and returns parsed extraction JSON "
        "plus a best-effort text summary.\n"
        "- generate_document_single: Generate one document from a template and data using the PDF4me GenerateDocumentSingle API. "
        "Supports template/data input modes (Docx/Html/Pdf/etc + Json/XML/Text), configurable output type (PDF/Docx/Html), "
        "optional async 202 polling, and output path selection; saves the generated file to disk.\n"
        "- generate_documents_multiple: Generate multiple documents from one template and data set using the PDF4me "
        "GenerateDocumentMultiple API. Supports Json/XML data, optional async 202 polling, and writes one or more output files "
        "to the selected directory.\n"
        "- read_barcodes: Read barcode and QR code data from a local PDF using the PDF4me ReadBarcodes API. "
        "Supports barcode type filtering and page selection; runs with async processing and returns structured barcode JSON.\n"
        "- read_barcodes_from_image: Read barcode and QR code data from a local image using the PDF4me ReadBarcodesfromImage API. "
        "Supports image type selection/inference, optional async 202 polling with Location resolution, and returns structured barcode JSON.\n"
        "- read_swiss_qr_bill: Read Swiss QR bill data from a local PDF using the PDF4me ReadSwissQRBill API. "
        "Supports optional async 202 polling with Location resolution and returns structured Swiss QR payload data as JSON.\n"
        "- remove_exif_tags_from_image: Remove EXIF metadata from a local image using the PDF4me RemoveEXIFTagsFromImage API. "
        "Supports JPG/PNG input, optional image type selection, optional async 202 polling, and output path selection; saves the cleaned image to disk.\n"
        "- replace_text_with_image: Replace text occurrences in a PDF with an image using the PDF4me ReplaceTextWithImage API. "
        "Accepts search text, page sequence, and image dimensions; supports optional async 202 polling and output path selection; saves the PDF to disk.\n"
        "- replace_text_with_image_in_word: Replace text in a Word document with an image using the PDF4me ReplaceTextWithImageInWord API. "
        "Accepts .doc/.docx input, search text, page numbers, optional first-page skip, optional async 202 polling, and output path selection; "
        "saves the modified Word file to disk.\n"
        "- rotate_image_by_exif_data: Auto-rotate a local image based on EXIF orientation using the PDF4me RotateImageByExifData API. "
        "Supports optional async 202 polling and output path selection; saves the corrected image to disk.\n"
        "- update_hyperlink_annotation: Update hyperlink annotations in a PDF using the PDF4me UpdateHyperlinkAnnotation API. "
        "Accepts search criteria and text/URL replacement values, supports optional async 202 polling and output path selection; saves the updated PDF to disk.\n"
        "- upload_file: Upload a local file to PDF4me storage using the PDF4me UploadFile API. "
        "Sends file name and base64 content, and returns structured upload response data (e.g. file reference metadata).\n"
        "- convert_ocr_pdf: Convert a PDF into a searchable/editable OCR PDF using the PDF4me ConvertOcrPdf API. "
        "Supports quality mode (Draft/High), language, OCR-when-needed behavior, optional async 202 polling, and optional output path; saves the OCR PDF to disk.\n"
        "- enable_tracking_changes_in_word: Enable Track Changes in a Word document via /api/v2/EnableTrackingChangesInWord. "
        "word_file_path (.docx/.doc), optional request_doc_name and output path; saves tracked Word output.\n"
        "- disable_tracking_changes_in_word: Disable Track Changes in a Word document via /api/v2/DisableTrackingChangesInWord. "
        "word_file_path (.docx/.doc), optional request_doc_name and output path; saves untracked Word output.\n"
        "- get_tracking_changes_in_word: Extract tracked change data via /api/v2/GetTrackingChangesInWord. "
        "word_file_path (.docx/.doc), optional request_doc_name and output path; saves tracking changes JSON/text output.\n"
    )
